apiVersion: v1
kind: Namespace
metadata:
  name: fin-agentix-india
  labels:
    name: fin-agentix-india
    environment: production
    compliance: rbi-compliant
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-quota
  namespace: fin-agentix-india
spec:
  hard:
    requests.cpu: "100"
    requests.memory: 200Gi
    limits.cpu: "200"
    limits.memory: 400Gi
    persistentvolumeclaims: "10"
